base:
  project: coronary_heart_deases
  random_state: 42
  target_column: target

data_source:
  s3_source: data_given/heart.csv

load_data: 
  raw_dataset_csv: data/raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89

model_dir: saved_models



